baseURL = "https://bcolucci.github.io/"
languageCode = "en-us"
title = "Brice Colucci - CV & Services"
theme = "PaperMod"
publishDir = "docs/"

[params]
  author = "Brice Colucci"
  description = "Senior Web Developer - Portfolio & Services"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
